package model.item;

import java.io.Serializable;

/**
 * Enum of book review taken from http://generi.librimondadori.it .
 *
 * @author Edoardo
 *
 */
public enum BookGenre implements Serializable {

    ART_FILM_MUSIC_ENTERTAINMENT, CURRENT_NEWS_REPORTS, WELLNESS_Selfhelp_LIFESTYLE, BIOGRAPHIES, CLASSICAL_CRITICISM, KITCHEN, FANTASY, THRILLER, GRAPHICNOVEL, HOBBY, FASHION, FICTION_MODERN_CONTEMPORARY, POETRY, POLICY, PSYCOLOGY_SOCIOLOGY, RELIGION, LOVE_NOVELS, TECHNOLOGY_SCIENCE, SPORT, ADVENTURE_HISTORY, HUMOR, TRAVEL_GUIDE
}
